/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-22 22:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ADMIN._04_005fCLIENT;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class client_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/ADMIN/04_CLIENT/../include/nav.jspf", Long.valueOf(1540244370115L));
    _jspx_dependants.put("jar:file:/C:/Users/1/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1540099427413L));
    _jspx_dependants.put("/WEB-INF/views/ADMIN/04_CLIENT/../include/header.jspf", Long.valueOf(1540236092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>고객사 관리</title>\r\n");
      out.write("<!-- 테이블관련 CSS/JS 시작 --------------------------------->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS-->\r\n");
      out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<link href=\"vendor/datatables/dataTables.bootstrap4.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/mainpage/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"vendor/datatables/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<script src=\"js/mainpage/sb-admin.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 테이블관련 CSS/JS 끝 -------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/include/subpage.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"js/include/subpage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- modal style 시작 -->\r\n");
      out.write("<style>\r\n");
      out.write(".modal-backdrop {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inputModal, #inputModal2 {\r\n");
      out.write("\ttop: 15%;\r\n");
      out.write("\tmargin-top: -50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#updateModal {\r\n");
      out.write("\ttop: 15%;\r\n");
      out.write("\tmargin-top: -50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* modal style 끝 */\r\n");
      out.write("#client_file {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 테이블 내용에서 고객사로 검색 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tvar input, filter, table, tr, td, i;\r\n");
      out.write("\t\tinput = document.getElementById(\"myInput\");\r\n");
      out.write("\t\tfilter = input.value.toUpperCase();\r\n");
      out.write("\t\ttable = document.getElementById(\"dataTable\");\r\n");
      out.write("\t\ttr = table.getElementsByTagName(\"tr\");\r\n");
      out.write("\t\tfor (i = 0; i < tr.length; i++) {\r\n");
      out.write("\t\t\ttd = tr[i].getElementsByTagName(\"td\")[2];\r\n");
      out.write("\t\t\tif (td) {\r\n");
      out.write("\t\t\t\tif (td.innerHTML.toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t\t\t\t\ttr[i].style.display = \"\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttr[i].style.display = \"none\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 테이블 내용에서 컬럼클릭시 정렬 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction sortTable(n) {\r\n");
      out.write("\t\tvar table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;\r\n");
      out.write("\t\ttable = document.getElementById(\"dataTable\");\r\n");
      out.write("\t\tswitching = true;\r\n");
      out.write("\r\n");
      out.write("\t\tdir = \"asc\";\r\n");
      out.write("\t\twhile (switching) {\r\n");
      out.write("\t\t\tswitching = false;\r\n");
      out.write("\t\t\trows = table.rows;\r\n");
      out.write("\t\t\tfor (i = 1; i < (rows.length - 1); i++) {\r\n");
      out.write("\t\t\t\tshouldSwitch = false;\r\n");
      out.write("\t\t\t\tx = rows[i].getElementsByTagName(\"td\")[n];\r\n");
      out.write("\t\t\t\ty = rows[i + 1].getElementsByTagName(\"td\")[n];\r\n");
      out.write("\t\t\t\tconsole.log(table);\r\n");
      out.write("\t\t\t\tif (dir == \"asc\") {\r\n");
      out.write("\t\t\t\t\tif (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {\r\n");
      out.write("\t\t\t\t\t\tshouldSwitch = true;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else if (dir == \"desc\") {\r\n");
      out.write("\t\t\t\t\tif (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {\r\n");
      out.write("\t\t\t\t\t\tshouldSwitch = true;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (shouldSwitch) {\r\n");
      out.write("\t\t\t\trows[i].parentNode.insertBefore(rows[i + 1], rows[i]);\r\n");
      out.write("\t\t\t\tswitching = true;\r\n");
      out.write("\t\t\t\tswitchcount++;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif (switchcount == 0 && dir == \"asc\") {\r\n");
      out.write("\t\t\t\t\tdir = \"desc\";\r\n");
      out.write("\t\t\t\t\tswitching = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 기존 리스트를 모달창에 불러오기 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".rowClick\").click(function(e) {\r\n");
      out.write("\t\t\tvar client_id = $(this).find(\".client_id\").html();\r\n");
      out.write("\t\t\tvar client_nm = $(this).find(\".client_nm\").html();\r\n");
      out.write("\t\t\tvar client_addr_1 = $(this).find(\".client_addr_1\").html();\r\n");
      out.write("\t\t\tvar client_addr_2 = $(this).find(\".client_addr_2\").val();\r\n");
      out.write("\t\t\tvar client_file_nm = $(this).find(\".client_file_nm\").html();\r\n");
      out.write("\t\t\tvar client_file = $(this).find(\".client_file\").html();\r\n");
      out.write("\r\n");
      out.write("\t\t\tconsole.log(client_id);\r\n");
      out.write("\t\t\tconsole.log(client_nm);\r\n");
      out.write("\t\t\tconsole.log(client_addr_1);\r\n");
      out.write("\t\t\tconsole.log(client_addr_2);\r\n");
      out.write("\t\t\tconsole.log(client_file_nm);\r\n");
      out.write("\t\t\tconsole.log(client_file);\r\n");
      out.write("\t\t\t/* var modalData = document.querySelectorAll('tbody a'); */\r\n");
      out.write("\t\t\t//var my_id_value = $(\".idClick\").eq(0).data(\"title\");\r\n");
      out.write("\t\t\t//var my_id_value2 = $(\".idClick\").eq(1).data(\"title1\");\r\n");
      out.write("\t\t\t$(\".modal-body #cli_id\").val(client_id);\r\n");
      out.write("\t\t\t$(\".modal-body #cli_nm\").val(client_nm);\r\n");
      out.write("\t\t\t$(\".modal-body #cli_addr_1\").val(client_addr_1);\r\n");
      out.write("\t\t\t$(\".modal-body #cli_addr_2\").val(client_addr_2);\r\n");
      out.write("\t\t\t$(\".modal-body #cli_file_nm\").val(client_file_nm);\r\n");
      out.write("\t\t\t$(\".modal-body #cli_file\").val(client_file);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/* $(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t $(\"#client_file\").on('change', function(){  // 값이 변경되면\r\n");
      out.write("\t if(window.FileReader){  // modern browser\r\n");
      out.write("\t var filename = $(this)[0].files[0].name;\r\n");
      out.write("\t } else {  // old IE\r\n");
      out.write("\t var filename = $(this).val().split('/').pop().split('\\\\').pop();  // 파일명만 추출\r\n");
      out.write("\t }\r\n");
      out.write("\t // 추출한 파일명 삽입\r\n");
      out.write("\t $(\"#userFile\").val(filename);\r\n");
      out.write("\t });\r\n");
      out.write("\t }); */\r\n");
      out.write("</script>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#cli_file\").on('change', function(){  // 값이 변경되면\r\n");
      out.write("\t\tif(window.FileReader){  // modern browser\r\n");
      out.write("\t\t\tvar filename = $(this)[0].files[0].name;\r\n");
      out.write("\t\t} else {  // old IE\r\n");
      out.write("\t\t\tvar filename = $(this).val().split('/').pop().split('\\\\').pop();  // 파일명만 추출\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// 추출한 파일명 삽입\r\n");
      out.write("\t\t$(\"#cli_file\").val(filename);\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <script>\r\n");
      out.write("/* 데이터 등록간 취소버튼 누를시 모달 초기화시키기 */\r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(\".modal\").on('hidden.bs.modal', function () {\r\n");
      out.write("         \talert('The modal is now hidden.');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).find('form')[0].reset();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("\t$('#myBtn').on('click','hidden.bs.modal', function (e) {\r\n");
      out.write("\t\tvar myBtn = document.getElementById(\"myBtn\")\r\n");
      out.write("\t    console.log('modal close');\r\n");
      out.write("\t  $(this).find('form')[0].reset()\r\n");
      out.write("\t});\r\n");
      out.write("\t</script> -->\r\n");
      out.write("<!-- <script>\r\n");
      out.write("function fileHidden() {\r\n");
      out.write("    document.getElementById(\"client_file\").style.overflow = \"hidden\";\r\n");
      out.write("}\r\n");
      out.write("</script> -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#updateBtn\").click(function() {\r\n");
      out.write("\t\t\tif(confirm(\"수정하시겠습니까?\") == true) //확인 \r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$(\"#modalForm\").attr(\"action\", \"/ClientUpdate\");\r\n");
      out.write("\t\t\t\t\t$(\"#modalForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#deleteBtn\").click(function() {\r\n");
      out.write("\t\t\tif(confirm(\"삭제하시겠습니까??\") == true)//삭제\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$(\"#modalForm\").attr(\"action\", \"/ClientDelete\");\r\n");
      out.write("\t\t\t\t\t$(\"#modalForm\").submit();\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 메뉴버튼눌렀을때 hover 유지 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#client').addClass('top_menu_active');\r\n");
      out.write("\t\t$('#client').find('i').addClass('menu_icon_active');\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- 메뉴버튼눌렀을때 hover 유지 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-------------------------------- body ---------------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.hidden_myPage > a { text-decoration: none;\r\n");
      out.write("    \tcolor: black;\r\n");
      out.write("      }\r\n");
      out.write("    .hidden_myPage > a:hover {color:white;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"title\"><a class=\"title_logo\" href=\"/\"><span>D</span>djy</a></div>\r\n");
      out.write("    <div id=\"myPage\">\r\n");
      out.write("       <img src=\"/img/subpage/admin.png\" id=\"profile_photo\" /> \r\n");
      out.write("       <span>관리자님</span>\r\n");
      out.write("       <i class=\"fa fa-angle-down down_arrow\" style=\"font-size:24px;\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hidden_myPage\">\r\n");
      out.write("\t       <!-- <div>정보변경</div> -->\r\n");
      out.write("\t       <div><a href=\"/Logout\">로그아웃</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main_templet\">\r\n");
      out.write("\t\t\t<div id=\"slide_btn\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- side_menu -->\r\n");
      out.write("\t\t\t<nav class=\"nav\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"top_menu_box\">\r\n");
      out.write("   <div id=\"commoncode\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-table menu_icon\"></i> \r\n");
      out.write("   \t\t<a href=\"/Commoncode\">신청관리</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"freeln\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-address-book-o\"></i>\r\n");
      out.write("  \t\t<a href=\"/Freeln\">프리랜서</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"project\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-calendar-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Project\">프로젝트</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"charge\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-user-circle\"></i>\r\n");
      out.write("   \t\t<a href=\"/Charge\">담당자</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"client\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-building-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Client\">고객사</a>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- main -->\r\n");
      out.write("\t\t\t<article>\r\n");
      out.write("\t\t\t\t<div class=\"tabs\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"content-wrapper\">\r\n");
      out.write("\t\t\t\t\t<!-- 테이블내용 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-fw fa-users\"></i> 고객사 관리\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"dataTable_wrapper\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dataTables_wrapper dt-bootstrap4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 col-md-11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"dataTable_filter\" class=\"dataTables_filter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>Search: <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"고객사를 입력하세요\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"myInput\" onkeyup=\"myFunction()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 col-md-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"myBtn\" data-toggle=\"modal\" data-target=\"#inputModal\">등록</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!------------------------------------------------- The Modal1 -------------------------------------------------->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal fade\" id=\"inputModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!--  <script>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\tvar changeFile = function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\tconsole.log(\"asdflhsaldfkjds\");\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\tconsole.log(document.getElementById(\"cli_file\"));\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\t//$(\"#cli_file\").val($(this).val());\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\tdocument.getElementById(\"cli_file\").value = e.value;\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t</script> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-content modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user icon\"></i>등록\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<form role=\"form\" action=\"/ClientInsert\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"client_nm\">고객사 이름</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_nm\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"client_nm\" placeholder=\"이름을 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"client_addr_1\">고객사 주소</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_addr_1\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"client_addr_1\" placeholder=\"주소를 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"client_addr_2\">고객사 상세주소</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_addr_2\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"client_addr_2\" placeholder=\"상세주소를 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"client_file_nm\">이력서 양식명</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_file_nm\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"client_file_nm\" placeholder=\"이력서 양식명을 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"client_file\">이력서 파일명</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"file\" name=\"client_file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control-file border\" id=\"client_file\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"form-group\" >\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"client_file\"> 이력서 파일명</label>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control-file border\" name=\"client_file\" id=\"client_file\" onchange=\"changeFile(this)\"\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\tdata-class-button=\"btn btn-default\" data-class-input=\"form-control\" data-icon-name=\"fa fa-upload\" class=\"form-control\" tabindex=\"-1\" style=\"position: absolute; clip: rect(0px 0px 0px 0px);\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-filestyle input-group\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"cli_file\" class=\"form-control\" name=\"userfile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"group-span-filestyle input-group-btn\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"client_file\" class=\"btn btn-default \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon fa fa-upload\"></span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t            </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-default pull-left\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"reset\" id=\"btnClose\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger btn-default pull-left\">초기화</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table class=\"table table-bordered dataTable\" id=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\twidth=\"100%\" cellspacing=\"0\" role=\"grid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\taria-describedby=\"dataTable_info\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr role=\"row\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(0)\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(1)\">고객사 아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(2)\">고객사명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(3)\">위치</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(4)\">이력서 양식명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(5)\">이력서 파일명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr role=\"row\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(0)\" rowspan=\"1\" colspan=\"1\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(1)\" rowspan=\"1\" colspan=\"1\">고객사\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(2)\" rowspan=\"1\" colspan=\"1\">고객사명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(3)\" rowspan=\"1\" colspan=\"1\">위치</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(4)\" rowspan=\"1\" colspan=\"1\">이력서\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t양식명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(5)\" rowspan=\"1\" colspan=\"1\">이력서\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t파일명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- The Modal2 데이터 수정 모달 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!----------------------------------------------- Modal2 ------------------------------------------------------>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal fade\" id=\"inputModal2\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Modal content2-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-content modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user icon\"></i>수정/삭제\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<form id=\"modalForm\" method=\"POST\" role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_id\">고객사 아이디</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"cli_id\" name=\"client_id\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_nm\">고객사 이름</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"client_nm\" class=\"form-control\" id=\"cli_nm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_addr_1\">고객사 주소</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_addr_1\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"cli_addr_1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_addr_2\">고객사 상세주소</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_addr_2\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"cli_addr_2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_file_nm\">이력서 양식명</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"client_file_nm\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"cli_file_nm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_file\">이력서 파일명</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"file\" name=\"client_file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control-file border\" id=\"cli_file\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"userFile\"> 이력서 파일명</label>\r\n");
      out.write("\t\t\t\t\t\t\t              <div class=\"bootstrap-filestyle input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\"class=\"form-control\" id=\"userFile\">\r\n");
      out.write("\t\t\t\t\t\t\t              \r\n");
      out.write("      \t\t\t\t\t\t\t\t\t  <input type=\"file\" class=\"form-control-file border\"  name=\"client_file\" id=\"cli_file\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t  <input type=\"file\" class=\"form-control-file border\"  name=\"client_file\" id=\"cli_file\" data-class-button=\"btn btn-default\" \r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\tdata-class-input=\"form-control\" data-icon-name=\"fa fa-upload\" class=\"form-control\" \r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\ttabindex=\"-1\" style=\"position: absolute; clip: rect(0px 0px 0px 0px);\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t\t<span class=\"group-span-filestyle input-group-btn\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cli_file\" class=\"btn btn-default \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon fa fa-upload\"></span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t  </div>\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"updateBtn\" value=\"수정\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-default pull-left\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"button\" id=\"deleteBtn\" value=\"삭제\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger btn-default pull-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 테이블내용 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/ADMIN/04_CLIENT/client.jsp(413,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("client");
      // /WEB-INF/views/ADMIN/04_CLIENT/client.jsp(413,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/04_CLIENT/client.jsp(413,13) '${clientList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${clientList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/ADMIN/04_CLIENT/client.jsp(413,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"rowClick\" role=\"row\" style=\"text-align: center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.rownum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"hidden\" class=\"client_addr_2\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#inputModal2\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.client_addr_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <a href=\"#\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"modal\" class=\"idClick client_id\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#inputModal2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.client_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"idClick client_nm\" data-target=\"#inputModal2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"idClick client_addr_1\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#inputModal2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.client_addr_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"idClick client_file_nm\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#inputModal2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.client_file_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"idClick client_file\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#inputModal2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${client.client_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
