/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-23 00:34:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ADMIN._01_005fFLEENL;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeln_005fdetail_005f01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/1/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1540099427413L));
    _jspx_dependants.put("/WEB-INF/views/ADMIN/01_FLEENL/../include/header.jspf", Long.valueOf(1540236092000L));
    _jspx_dependants.put("/WEB-INF/views/ADMIN/01_FLEENL/../include/nav.jspf", Long.valueOf(1540244370115L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>DDJY University</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 테이블관련 CSS/JS 시작 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core CSS-->\r\n");
      out.write("\t<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"vendor/datatables/dataTables.bootstrap4.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/mainpage/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"vendor/datatables/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("    <script src=\"js/mainpage/sb-admin.min.js\"></script>\r\n");
      out.write("    <script src=\"js/demo/datatables-demo.js\"></script>\r\n");
      out.write("    <script src=\"js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("  \t<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \t<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 테이블관련 CSS/JS 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/include/freeln_detail_01.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/include/subpage.css\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- js -->\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/include/subpage.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#freeln').addClass('top_menu_active');\r\n");
      out.write("\t\t$('#freeln').find('i').addClass('menu_icon_active');\r\n");
      out.write("\t\t/* $('.btn-group > button:nth-of-type(1)').focus(); */\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-------------------------------- body ---------------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<!-- header -->\r\n");
      out.write("  <header>\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.hidden_myPage > a { text-decoration: none;\r\n");
      out.write("    \tcolor: black;\r\n");
      out.write("      }\r\n");
      out.write("    .hidden_myPage > a:hover {color:white;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"title\"><a class=\"title_logo\" href=\"/\"><span>D</span>djy</a></div>\r\n");
      out.write("    <div id=\"myPage\">\r\n");
      out.write("       <img src=\"/img/subpage/admin.png\" id=\"profile_photo\" /> \r\n");
      out.write("       <span>관리자님</span>\r\n");
      out.write("       <i class=\"fa fa-angle-down down_arrow\" style=\"font-size:24px;\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hidden_myPage\">\r\n");
      out.write("\t       <!-- <div>정보변경</div> -->\r\n");
      out.write("\t       <div><a href=\"/Logout\">로그아웃</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </header>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"main_templet\">\r\n");
      out.write("  <div id=\"slide_btn\"></div>\r\n");
      out.write("  \r\n");
      out.write("<!-- side_menu -->\r\n");
      out.write("  <nav class=\"nav\">\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"top_menu_box\">\r\n");
      out.write("   <div id=\"commoncode\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-table menu_icon\"></i> \r\n");
      out.write("   \t\t<a href=\"/Commoncode\">신청관리</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"freeln\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-address-book-o\"></i>\r\n");
      out.write("  \t\t<a href=\"/Freeln\">프리랜서</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"project\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-calendar-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Project\">프로젝트</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"charge\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-user-circle\"></i>\r\n");
      out.write("   \t\t<a href=\"/Charge\">담당자</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"client\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-building-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Client\">고객사</a>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("<!-- main -->\r\n");
      out.write("  <article>\r\n");
      out.write("   \t<div class=\"tabs\">\r\n");
      out.write("    </div>\r\n");
      out.write("    \t\r\n");
      out.write("    <div class=\"sections\">\r\n");
      out.write("    <!-- 내용넣기! -->\r\n");
      out.write("      <ul class=\"breadcrumb\">\r\n");
      out.write("\t    <li class=\"active\">기본정보</li>\r\n");
      out.write("\t    <li><a href=\"/FreelnDetail02?freeln_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">기술정보</a></li>\r\n");
      out.write("\t    <li><a href=\"/FreelnDetail03?freeln_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">경력정보</a></li>\r\n");
      out.write("\t    <li><a href=\"/FreelnDetail04?freeln_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">통화내역</a></li>        \r\n");
      out.write("\t    <li><a href=\"/Freeln\">목록으로</a></li>        \r\n");
      out.write("\t  </ul>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div id=\"content-wrapper\">\r\n");
      out.write("\t  <div class=\"card mb-3\">\r\n");
      out.write("\t <div class=\"card-header\">\r\n");
      out.write("   \t\t\t<i class=\"fas fa-fw fa-users\"></i>\r\n");
      out.write("   \t\t\t프리랜서 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 기본정보\r\n");
      out.write("     </div>\r\n");
      out.write("\t <table class=\"table table-bordered\">\r\n");
      out.write("\t    <tbody>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>이름</th>\r\n");
      out.write("\t        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t        <td rowspan=\"5\" id=\"photo_can\"> \r\n");
      out.write("\t        \t<img src=\"/img/subpage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.img_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t        </td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>아이디</th>\r\n");
      out.write("\t        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>핸드폰</th>\r\n");
      out.write("\t        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>자택전화</th>\r\n");
      out.write("\t        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freeln_tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>이메일</th>\r\n");
      out.write("\t        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freen_mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>주소</th>\r\n");
      out.write("\t        <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freen_addr_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.freen_addr_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>희망 근무지</th>\r\n");
      out.write("\t        <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.hope_place}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>희망 단가</th>\r\n");
      out.write("\t        <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.hope_money}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <th>투입 가능일</th>\r\n");
      out.write("\t        <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.in_enable_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>      \r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancer.note}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t    </tbody>\r\n");
      out.write("\t  </table>\r\n");
      out.write("    </div>\r\n");
      out.write("       </div> \t\r\n");
      out.write("   </div>\r\n");
      out.write("  </article>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t/*  $(function(){\r\n");
      out.write("\t\t$('nav').on('click','a',function(e){\r\n");
      out.write("\t\t\t//alert('plus clicked');\r\n");
      out.write("\t\t\t e.preventDefault(); + e.stopPropagation();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}); */ \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
