select * from charge_tbl
;
select * from project_tbl;

     SELECT
      
        ROWNUM, T1.PROJ_ID, T2.CHARGE_ID, T1.PROJ_NM, TO_CHAR(T1.PROJ_STR_DATE,'YYYY-MM-DD') AS PROJ_STR_DATE,
        TO_CHAR(T1.PROJ_END_DATE,'YYYY-MM-DD') AS PROJ_END_DATE, T1.CLIENT_ID, T1.NEED_TECH, T1.FIELD_1,
        T1.FIELD_2,T1.INVOLVE_NUM, T2.CHARGE_NM, T1.REMARK, T4.CLIENT_NM, T1.PROJECT_AMOUNT

      FROM
        PROJECT_TBL T1, CHARGE_TBL T2, PROJ_CHR_TBL T3, CLIENT_TBL T4
        
       WHERE T1.PROJ_ID = T3.PROJECT_ID(+)
         AND T2.CHARGE_ID(+) = T3.CHARGE_ID
         AND T1.CLIENT_ID = T4.CLIENT_ID(+);
         
         
         
         
         
CREATE TABLE UPLOADFILE
(
    IDX NUMBER PRIMARY KEY,
    ORIGINAL_FILE_NAME VARCHAR2(260) NOT NULL,
    STORED_FILE_NAME VARCHAR2(36) NOT NULL,
    FILE_SIZE NUMBER,
    CREA_DTM DATE DEFAULT SYSDATE NOT NULL,
    CREA_ID VARCHAR2(30) NOT NULL,
    DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE SEQUENCE SEQ_UPLOADFILE_IDX
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE;

COMMIT;

