/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-22 20:27:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.FREELNMAIN;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freelnMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/1/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1540099427413L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Freelancer - Start Bootstrap Theme</title>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"vendor/freelnMain/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template -->\r\n");
      out.write("    <link href=\"vendor/freelnMain/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin CSS -->\r\n");
      out.write("    <link href=\"vendor/freelnMain/magnific-popup/magnific-popup.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"css/freelnMain/freelancer.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \ta:hover {text-decoration: none;}\r\n");
      out.write("    \tli>a {color:white;}\r\n");
      out.write("    \tli>a:hover {color:white; font-weight: bolder;}\r\n");
      out.write("    \tli {display: inline-block;\r\n");
      out.write("\t\t    list-style: none;\r\n");
      out.write("\t\t    padding: 10px;}\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("    \t$('.btn_signUp').on('click',function(e){\r\n");
      out.write("   \t\t \r\n");
      out.write("  \t\t  \r\n");
      out.write("  \t\t  var href = $(this).attr('href');\t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t  //ajax 호출 : db 조회\r\n");
      out.write("  \t\t  $.ajax({\r\n");
      out.write("  \t\t\t  url  \t   : href,\r\n");
      out.write("  \t\t\t  type \t   : 'GET',\r\n");
      out.write("  \t\t\t  dataType : 'json',\r\n");
      out.write("  \t\t\t  success  : function(result_val){\r\n");
      out.write("  \t\t\t\tconsole.log(result_val);\r\n");
      out.write("  \t\t\t\t  //alert(gugunList);\r\n");
      out.write("  \t\t\t\t  if(result_val == 0){\r\n");
      out.write("  \t\t\t\t\t  alert(\"이미 신청한 프로젝트입니다\");\r\n");
      out.write("  \t\t\t\t  } else{\r\n");
      out.write("  \t\t\t\t\talert(\"신청되었습니다\");\r\n");
      out.write("  \t\t\t\t  }\r\n");
      out.write("  \t\t\t  },\r\n");
      out.write("  \t\t\t  error\t   : function(xhr){\r\n");
      out.write("  \t\t\t\t  console.log(xhr);\r\n");
      out.write("  \t\t\t\t  alert('에러발생 : ' + xhr.status);\r\n");
      out.write("  \t\t\t  }\r\n");
      out.write("  \t\t  });\r\n");
      out.write("  \t\t return false;\r\n");
      out.write("  \t  }); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 메뉴 -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-secondary fixed-top text-uppercase\" id=\"mainNav\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">DDJY</a>\r\n");
      out.write("        <button class=\"navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          Menu\r\n");
      out.write("          <i class=\"fas fa-bars\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            <li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("              <a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#portfolio\">My Career</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("              <a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" \r\n");
      out.write("              \t\thref=\"/ModifyMyInfo?freeln_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeln_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("              My Info\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("           <!--  <li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("              <a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"\">Chat</a>\r\n");
      out.write("            </li>  -->\r\n");
      out.write("            <li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("              <a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"/Logout\">Logout</a>\r\n");
      out.write("            </li> \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- 프로젝트 리스트 -->\r\n");
      out.write("    <header class=\"masthead bg-primary text-white text-center portfolio\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center text-uppercase mb-0\">Project List</h2>\r\n");
      out.write("        <hr class=\"star-light\">\r\n");
      out.write("        \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\t\t\t<!-- <ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">1</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">2</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">3</a></li>\r\n");
      out.write("\t\t\t</ul> -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 프로젝트 상세 보기 Modals -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 내가 참여했던 프젝 -->\r\n");
      out.write("    <section class=\"portfolio\" id=\"portfolio\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center text-uppercase text-secondary mb-0\">My Career</h2>\r\n");
      out.write("        <hr class=\"star-dark mb-5\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 내 커리어 상세 보기 Modals -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- About Section -->\r\n");
      out.write("    <!-- <section class=\"bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center text-uppercase text-white\">About</h2>\r\n");
      out.write("        <hr class=\"star-light mb-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4 ml-auto\">\r\n");
      out.write("            <p class=\"lead\">Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 mr-auto\">\r\n");
      out.write("            <p class=\"lead\">Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center mt-4\">\r\n");
      out.write("          <a class=\"btn btn-xl btn-outline-light\" href=\"#\">\r\n");
      out.write("            <i class=\"fas fa-download mr-2\"></i>\r\n");
      out.write("            Download Now!\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Section -->\r\n");
      out.write("    <!-- <section id=\"contact\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center text-uppercase text-secondary mb-0\">Contact Me</h2>\r\n");
      out.write("        <hr class=\"star-dark mb-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("            To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.\r\n");
      out.write("            The form should work on most web servers, but if the form is not working you may need to configure your web server differently.\r\n");
      out.write("            <form name=\"sentMessage\" id=\"contactForm\" novalidate=\"novalidate\">\r\n");
      out.write("              <div class=\"control-group\">\r\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                  <label>Name</label>\r\n");
      out.write("                  <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Name\" required=\"required\" data-validation-required-message=\"Please enter your name.\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"control-group\">\r\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                  <label>Email Address</label>\r\n");
      out.write("                  <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Email Address\" required=\"required\" data-validation-required-message=\"Please enter your email address.\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"control-group\">\r\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                  <label>Phone Number</label>\r\n");
      out.write("                  <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Phone Number\" required=\"required\" data-validation-required-message=\"Please enter your phone number.\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"control-group\">\r\n");
      out.write("                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                  <label>Message</label>\r\n");
      out.write("                  <textarea class=\"form-control\" id=\"message\" rows=\"5\" placeholder=\"Message\" required=\"required\" data-validation-required-message=\"Please enter a message.\"></textarea>\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <br>\r\n");
      out.write("              <div id=\"success\"></div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-xl\" id=\"sendMessageButton\">Send</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <!-- <footer class=\"footer text-center\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 mb-5 mb-lg-0\">\r\n");
      out.write("            <h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("            <p class=\"lead mb-0\">2215 John Daniel Drive\r\n");
      out.write("              <br>Clark, MO 65243</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 mb-5 mb-lg-0\">\r\n");
      out.write("            <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\r\n");
      out.write("            <ul class=\"list-inline mb-0\">\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-fw fa-facebook-f\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-fw fa-google-plus-g\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-fw fa-twitter\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-fw fa-linkedin-in\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a class=\"btn btn-outline-light btn-social text-center rounded-circle\" href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-fw fa-dribbble\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <h4 class=\"text-uppercase mb-4\">About Freelancer</h4>\r\n");
      out.write("            <p class=\"lead mb-0\">Freelance is a free to use, open source Bootstrap theme created by\r\n");
      out.write("              <a href=\"http://startbootstrap.com\">Start Bootstrap</a>.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <small>Copyright &copy; Your Website 2018</small>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->\r\n");
      out.write("    <div class=\"scroll-to-top d-lg-none position-fixed \">\r\n");
      out.write("      <a class=\"js-scroll-trigger d-block text-center text-white rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fa fa-chevron-up\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("    <!-- Portfolio Modal 2 -->\r\n");
      out.write("    <!-- <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-2\">\r\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\r\n");
      out.write("              <hr class=\"star-dark mb-5\">\r\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/freelnMain/portfolio/cake.png\" alt=\"\">\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-close\"></i>\r\n");
      out.write("                Close Project</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Portfolio Modal 3 -->\r\n");
      out.write("    <!-- <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-3\">\r\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\r\n");
      out.write("              <hr class=\"star-dark mb-5\">\r\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/freelnMain/portfolio/circus.png\" alt=\"\">\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-close\"></i>\r\n");
      out.write("                Close Project</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Portfolio Modal 4 -->\r\n");
      out.write("    <!-- <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-4\">\r\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\r\n");
      out.write("              <hr class=\"star-dark mb-5\">\r\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/freelnMain/portfolio/game.png\" alt=\"\">\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-close\"></i>\r\n");
      out.write("                Close Project</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Portfolio Modal 5 -->\r\n");
      out.write("    <!-- <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-5\">\r\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\r\n");
      out.write("              <hr class=\"star-dark mb-5\">\r\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/freelnMain/portfolio/safe.png\" alt=\"\">\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-close\"></i>\r\n");
      out.write("                Close Project</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Portfolio Modal 6 -->\r\n");
      out.write("    <!-- <div class=\"portfolio-modal mfp-hide\" id=\"portfolio-modal-6\">\r\n");
      out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
      out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <h2 class=\"text-secondary text-uppercase mb-0\">Project Name</h2>\r\n");
      out.write("              <hr class=\"star-dark mb-5\">\r\n");
      out.write("              <img class=\"img-fluid mb-5\" src=\"img/freelnMain/portfolio/submarine.png\" alt=\"\">\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("              <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-close\"></i>\r\n");
      out.write("                Close Project</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript -->\r\n");
      out.write("    <script src=\"vendor/freelnMain/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/freelnMain/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin JavaScript -->\r\n");
      out.write("    <script src=\"vendor/freelnMain/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/freelnMain/magnific-popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Form JavaScript -->\r\n");
      out.write("    <script src=\"js/freelnMain/jqBootstrapValidation.js\"></script>\r\n");
      out.write("    <script src=\"js/freelnMain/contact_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for this template -->\r\n");
      out.write("    <script src=\"js/freelnMain/freelancer.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(127,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("projectList");
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(127,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/FREELNMAIN/freelnMain.jsp(127,8) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(127,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("          <div class=\"col-md-6 col-lg-4\">\r\n");
            out.write("            <a class=\"portfolio-item d-block mx-auto\" href=\"#projectList-modal-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("              <div class=\"portfolio-item-caption d-flex position-absolute h-100 w-100\">\r\n");
            out.write("                <div class=\"portfolio-item-caption-content my-auto w-100 text-center text-white\">\r\n");
            out.write("                  <i class=\"fas fa-search-plus fa-3x\"></i>\r\n");
            out.write("                </div>\r\n");
            out.write("              </div>\r\n");
            out.write("             <!-- <img class=\"img-fluid\" src=\"img/freelnMain/portfolio/cabin.png\" alt=\"\"> -->\r\n");
            out.write("              \t<table style=\"width:350px; height:252.77px; background-color:white; color:#334D5C;\">\r\n");
            out.write("              \t\t<tr>\r\n");
            out.write("              \t\t\t<td colspan=\"2\" style=\"padding-top:20px;\">\r\n");
            out.write("              \t\t\t\t<h4 class=\"text-uppercase mb-0\" style=\"color:#BA4C63\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("              \t\t\t\t");
            out.write("\r\n");
            out.write("              \t\t\t</td>\r\n");
            out.write("              \t\t</tr>\r\n");
            out.write("              \t\t<tr>\r\n");
            out.write("              \t\t\t<td colspan=\"2\">\r\n");
            out.write("              \t\t\t\t<h2 class=\"font-weight-light mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.need_tech}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\r\n");
            out.write("              \t\t\t</td>\r\n");
            out.write("              \t\t</tr>\r\n");
            out.write("              \t\t\r\n");
            out.write("              \t\t<tr>\r\n");
            out.write("              \t\t\t<td colspan=\"2\" style=\"padding-bottom:20px;\">\r\n");
            out.write("              \t\t\t<p class=\"lead mb-0\">예상 프로젝트 금액  \r\n");
            out.write("              \t\t\t<span style=\"color:#18bc9c\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.project_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></p>\r\n");
            out.write("              \t\t\t</td>\r\n");
            out.write("              \t\t</tr>\r\n");
            out.write("              \t</table>\r\n");
            out.write("            </a>\r\n");
            out.write("          </div>\r\n");
            out.write("          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(165,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("projectList");
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(165,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/FREELNMAIN/freelnMain.jsp(165,4) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(165,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"projectList-modal-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
            out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
            out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
            out.write("        </a>\r\n");
            out.write("        <div class=\"container text-center\">\r\n");
            out.write("          <div class=\"row\">\r\n");
            out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
            out.write("              <h3 class=\"text-secondary text-uppercase mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("              <hr class=\"star-dark mb-5\">\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">프로젝트 기간 | </span> \r\n");
            out.write("              \t ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_str_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('~');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">비용 | </span>  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.project_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">위치(회사 이름) | </span>\r\n");
            out.write("                ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.client_addr_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.client_addr_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('(');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">투여 인원 | </span>  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.involve_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" 명</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">필요 기술 | </span>  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.need_tech}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">상세 내용</span><br/>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.remark}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <!-- <p class=\"mb-5\"><span class=\"lead mb-0\">월 급여 |</span>  </p> -->\r\n");
            out.write("      \r\n");
            out.write("           \t  <a class=\"btn btn-primary btn-lg btn_signUp\" \r\n");
            out.write("           \t  \t\thref=\"/ProjectSignUp?freeln_id=&project_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.proj_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                <i class=\"fa fa-close\"></i>\r\n");
            out.write("                Sign up\r\n");
            out.write("              </a>\r\n");
            out.write("              \r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("    </div>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(208,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("freelancerCareer");
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(208,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/FREELNMAIN/freelnMain.jsp(208,8) '${freelancerCareer}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${freelancerCareer}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(208,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("          <div class=\"col-md-6 col-lg-4\">\r\n");
            out.write("            <a class=\"portfolio-item d-block mx-auto\" href=\"#career-modal-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.career_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("              <div class=\"portfolio-item-caption d-flex position-absolute h-100 w-100\">\r\n");
            out.write("                <div class=\"portfolio-item-caption-content my-auto w-100 text-center text-white\">\r\n");
            out.write("                  <i class=\"fas fa-search-plus fa-3x\"></i>\r\n");
            out.write("                </div>\r\n");
            out.write("              </div>\r\n");
            out.write("             <!--  <img class=\"img-fluid\" src=\"img/freelnMain/portfolio/cabin.png\" alt=\"\"> -->\r\n");
            out.write("             <table style=\"width:350px; height:252.77px; background-color:#18BC9C; color:white; text-align:center;\">\r\n");
            out.write("              \t\t<tr>\r\n");
            out.write("              \t\t\t<td colspan=\"2\" style=\"padding-top:20px;\">\r\n");
            out.write("              \t\t\t\t<h4 class=\"text-uppercase mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("              \t\t\t\t");
            out.write("\r\n");
            out.write("              \t\t\t</td>\r\n");
            out.write("              \t\t</tr>\r\n");
            out.write("              \t\t<tr>\r\n");
            out.write("              \t\t\t<td colspan=\"2\">\r\n");
            out.write("              \t\t\t\t<h3 class=\"font-weight-light mb-0\">\r\n");
            out.write("              \t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.use_tech_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.use_tech_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("              \t\t\t\t</h3>\r\n");
            out.write("              \t\t\t\t\r\n");
            out.write("              \t\t\t</td>\r\n");
            out.write("              \t\t</tr>\r\n");
            out.write("              \t\t\r\n");
            out.write("              \t\t<tr>\r\n");
            out.write("              \t\t\t<td colspan=\"2\" style=\"padding-bottom:20px;\">\r\n");
            out.write("              \t\t\t<p class=\"lead mb-0\">금액  \r\n");
            out.write("              \t\t\t<span style=\"color:#334D5C\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.work_money}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></p>\r\n");
            out.write("              \t\t\t</td>\r\n");
            out.write("              \t\t</tr>\r\n");
            out.write("              \t</table>\r\n");
            out.write("            </a>\r\n");
            out.write("          </div>\r\n");
            out.write("          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(248,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("freelancerCareer");
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(248,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/FREELNMAIN/freelnMain.jsp(248,4) '${freelancerCareer}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${freelancerCareer}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/FREELNMAIN/freelnMain.jsp(248,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"portfolio-modal mfp-hide\" id=\"career-modal-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.career_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("      <div class=\"portfolio-modal-dialog bg-white\">\r\n");
            out.write("        <a class=\"close-button d-none d-md-block portfolio-modal-dismiss\" href=\"#\">\r\n");
            out.write("          <i class=\"fa fa-3x fa-times\"></i>\r\n");
            out.write("        </a>\r\n");
            out.write("        <div class=\"container text-center\">\r\n");
            out.write("          <div class=\"row\">\r\n");
            out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
            out.write("              <h3 class=\"text-secondary text-uppercase mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("              <hr class=\"star-dark mb-5\">\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">사용 기술 | </span> \r\n");
            out.write("              \t ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.use_tech_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.use_tech_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">직책 | </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.duty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">업무 | </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.task}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">프로젝트 기간 | </span> \r\n");
            out.write("              \t ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.work_str_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('~');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.work_end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">한달 급여 | </span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.work_money}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">위치 | </span>\r\n");
            out.write("                ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.client_loca_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('~');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.client_loca_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <p class=\"mb-5\"><span class=\"lead mb-0\">상세 내용</span><br/>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freelancerCareer.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("              <!-- <p class=\"mb-5\"><span class=\"lead mb-0\">월 급여 |</span>  </p> -->\r\n");
            out.write("      \r\n");
            out.write("           \t  <a class=\"btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss\" href=\"#\">\r\n");
            out.write("                <i class=\"fa fa-close\"></i>\r\n");
            out.write("                Close Project</a>\r\n");
            out.write("              \r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("    </div>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }
}
