/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-22 22:51:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ADMIN._02_005fPROJECT;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class project_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/ADMIN/02_PROJECT/../include/header.jspf", Long.valueOf(1540236092000L));
    _jspx_dependants.put("/WEB-INF/views/ADMIN/02_PROJECT/../include/nav.jspf", Long.valueOf(1540244370115L));
    _jspx_dependants.put("jar:file:/C:/Users/1/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1540099427413L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>DDJY University</title>\r\n");
      out.write("<!-- 테이블관련 CSS/JS 시작 -->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS-->\r\n");
      out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<link href=\"vendor/datatables/dataTables.bootstrap4.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/mainpage/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"vendor/datatables/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<script src=\"js/mainpage/sb-admin.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 테이블관련 CSS/JS 끝 -->\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/include/subpage.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/project/project.css\"/> -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"js/include/subpage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- datepicker를 위한 CSS/JS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\t<!-- <link rel=\"stylesheet\" href=\"/resources/demos/style.css\"> -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\t<!-- datepicker를 위한 CSS/JS 끝-->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#project').addClass('top_menu_active');\r\n");
      out.write("\t\t$('#project').find('i').addClass('menu_icon_active');\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".modal-backdrop {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inputModal {\r\n");
      out.write("\ttop: 15%;\r\n");
      out.write("\tmargin-top: -50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#updateModal {\r\n");
      out.write("\ttop: 15%;\r\n");
      out.write("\tmargin-top: -50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-responsive {\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".idClick {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 테이블 내용에서 프로젝트명으로 검색 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tvar input, filter, table, tr, td, i;\r\n");
      out.write("\t\tinput = document.getElementById(\"myInput\");\r\n");
      out.write("\t\tfilter = input.value.toUpperCase();\r\n");
      out.write("\t\ttable = document.getElementById(\"dataTable\");\r\n");
      out.write("\t\ttr = table.getElementsByTagName(\"tr\");\r\n");
      out.write("\t\t/*   proj_nm = $('.proj_nm');\r\n");
      out.write("\t\t project_str_date = $('.project_str_date');\r\n");
      out.write("\t\t project_end_date = $('.project_end_date');\r\n");
      out.write("\t\t client_nm = $('.client_nm'); \r\n");
      out.write("\t\t need_tech = $('.need_tech');\r\n");
      out.write("\t\t field_1 = $('.field_1');\r\n");
      out.write("\t\t involve_num = $('.involve_num');\r\n");
      out.write("\t\t charge_id = $('.charge_id'); */\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i < tr.length; i++) {\r\n");
      out.write("\t\t\ttd = tr[i].getElementsByTagName(\"td\")[1];\r\n");
      out.write("\t\t\tif (td) {\r\n");
      out.write("\t\t\t\tif (td.innerHTML.toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t\t\t\t\ttr[i].style.display = \"\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttr[i].style.display = \"none\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* \t  console.log(client_nm.eq(i).html());\r\n");
      out.write("\t console.log(project_str_date.eq(1).html());\r\n");
      out.write("\t\r\n");
      out.write("\t if (proj_nm.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t else if(project_str_date.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t } else if(project_end_date.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:'); \r\n");
      out.write("\t } else if(client_nm.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t } else if(need_tech.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t } else if(field_1.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t } else if(involve_num.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t } else if(charge_id.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t tr.eq(i).attr('style','display:');\r\n");
      out.write("\t } else {\r\n");
      out.write("\t tr.eq(i).attr('style','display:none');\r\n");
      out.write("\t }\r\n");
      out.write("\t }\r\n");
      out.write("\t } */\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 테이블 내용에서 컬럼클릭시 정렬 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction sortTable(n) {\r\n");
      out.write("\t\tvar table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;\r\n");
      out.write("\t\ttable = document.getElementById(\"dataTable\");\r\n");
      out.write("\t\tswitching = true;\r\n");
      out.write("\t\tdir = \"asc\";\r\n");
      out.write("\t\twhile (switching) {\r\n");
      out.write("\t\t\tswitching = false;\r\n");
      out.write("\t\t\trows = table.rows;\r\n");
      out.write("\t\t\tconsole.log(rows);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor (i = 1; i < (rows.length - 2); i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tshouldSwitch = false;\r\n");
      out.write("\t\t\t\tx = rows[i].getElementsByTagName(\"A\")[n];\r\n");
      out.write("\t\t\t\ty = rows[i + 1].getElementsByTagName(\"A\")[n];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tconsole.log(table);\r\n");
      out.write("\t\t\t\tconsole.log(x);\r\n");
      out.write("\t\t\t\tconsole.log(y);\r\n");
      out.write("\t\t\t\tconsole.log(n);\r\n");
      out.write("\t\t\t\tif (dir == \"asc\") {\r\n");
      out.write("\t\t\t\t\tif (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {\r\n");
      out.write("\t\t\t\t\t\tshouldSwitch = true;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else if (dir == \"desc\") {\r\n");
      out.write("\t\t\t\t\tif (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {\r\n");
      out.write("\t\t\t\t\t\tshouldSwitch = true;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (shouldSwitch) {\r\n");
      out.write("\t\t\t\trows[i].parentNode.insertBefore(rows[i + 1], rows[i]);\r\n");
      out.write("\t\t\t\tswitching = true;\r\n");
      out.write("\t\t\t\tswitchcount ++;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif (switchcount == 0 && dir == \"asc\") {\r\n");
      out.write("\t\t\t\t\tdir = \"desc\";\r\n");
      out.write("\t\t\t\t\tswitching = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 기존 리스트를 모달창에 불러오기 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".rowClick\").click(function(e) {\r\n");
      out.write("\t\t\tvar project_id = $(this).find(\".proj_id\").val();\r\n");
      out.write("\t\t\tvar charge_id = $(this).find(\".charge_id\").val();\r\n");
      out.write("\t\t\tvar project_nm = $(this).find(\".proj_nm\").html();\r\n");
      out.write("\t\t\tvar project_str_date = $(this).find(\".proj_str_date\").html();\r\n");
      out.write("\t\t\tvar project_end_date = $(this).find(\".proj_end_date\").html();\r\n");
      out.write("\t\t\tvar client_id = $(this).find(\".client_id\").val();\r\n");
      out.write("\t\t\tvar involve_num = $(this).find(\".involve_num\").html();\r\n");
      out.write("\t\t\tvar field_1 = $(this).find(\".field_1\").html();\r\n");
      out.write("\t\t\tvar field_2 = $(this).find(\".field_2\").val();\r\n");
      out.write("\t\t\tvar remark = $(this).find(\".remark\").children(\"p\").html();\r\n");
      out.write("\t\t\tvar project_amount = $(this).find(\".project_amount\").html();\r\n");
      out.write("\t\t\tvar need_tech = $(this).find(\".need_tech\").html();\r\n");
      out.write("\t \t    var client_nm = $(this).find(\".client_nm\").html();   \r\n");
      out.write("\r\n");
      out.write("\t\t\tconsole.log(proj_id);\r\n");
      out.write("\t\t\tconsole.log(proj_nm);\r\n");
      out.write("\t\t\tconsole.log(proj_str_date);\r\n");
      out.write("\t\t\tconsole.log(proj_end_date);\r\n");
      out.write("\t\t\tconsole.log('고객사'+client_id);\r\n");
      out.write("\t\t\tconsole.log(involve_num);\r\n");
      out.write("\t\t\tconsole.log(field_1);\r\n");
      out.write("\t\t\tconsole.log(field_2);\r\n");
      out.write("\t\t\tconsole.log(remark);\r\n");
      out.write("\t\t\tconsole.log(project_amount);\r\n");
      out.write("\t\t\tconsole.log(need_tech);\r\n");
      out.write("\t \t\tconsole.log(client_nm); \r\n");
      out.write("\t\t\t/* \r\n");
      out.write("\t\t\tvar option = $(\"option[value=\"+charge_id+\"]\",\".modal-body #char_id\");\r\n");
      out.write("\t\t\tconsole.log(\"option!!!\"+option.html());\r\n");
      out.write("\t\t\tvar option = $(\"option[value=\"+client_id+\"]\",\".modal-body #cli_id\");\r\n");
      out.write("\t\t\tconsole.log(\"option!!!\"+option.html()); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* console.log(use_yn); */\r\n");
      out.write("\t\t\t/* var modalData = document.querySelectorAll('tbody a'); */\r\n");
      out.write("\t\t\t//var my_id_value = $(\".idClick\").eq(0).data(\"title\");\r\n");
      out.write("\t\t\t//var my_id_value2 = $(\".idClick\").eq(1).data(\"title1\");\r\n");
      out.write("\t\t\t$(\".modal-body #proj_id\").val(project_id);\r\n");
      out.write("\t\t\t$(\".modal-body #proj_nm\").val(project_nm);\r\n");
      out.write("\t\t\t/* $(\".modal-body #char_id\").val(charge_id); */\r\n");
      out.write("\t\t\t$(\"option[value=\"+charge_id+\"]\",\".modal-body #char_id\").prop(\"selected\", true);\r\n");
      out.write("\t\t\t$(\".modal-body #proj_str_date\").val(project_str_date);\r\n");
      out.write("\t\t\t$(\".modal-body #proj_end_date\").val(project_end_date);\r\n");
      out.write("\t\t\t/* $(\".modal-body #cli_id\").val(client_id); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"option[value=\"+client_id+\"]\",\".modal-body #cli_id\").prop(\"selected\", true);\r\n");
      out.write("\t\t\t$(\".modal-body #inv_num\").val(involve_num);\r\n");
      out.write("\t\t\t$(\".modal-body #fid_1\").val(field_1);\r\n");
      out.write("\t\t\t$(\".modal-body #fid_2\").val(field_2);\r\n");
      out.write("\t\t\t$(\".modal-body #rmark\").val(remark);\r\n");
      out.write("\t\t\t$(\".modal-body #proj_amount\").val(project_amount);\r\n");
      out.write("\t\t\t$(\".modal-body #need_tec\").val(need_tech);\r\n");
      out.write("\t \t \t $(\".modal-body #cli_nm\").val(client_nm);  \r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#deletebtn\").click(function() {\r\n");
      out.write("\t\t\tif(confirm(\"정말 삭제하시겠습니까??\")==true)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$(\"#modalform\").attr(\"action\", \"/ProjectDelete\");\r\n");
      out.write("\t\t\t\t\t$(\"#modalform\").submit();\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#updatebtn\").click(function() {\r\n");
      out.write("\t\t\tif(confirm(\"정말 수정하시겠습니까?\")==true)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$(\"#modalform\").attr(\"action\", \"/ProjectUpdate\");\r\n");
      out.write("\t\t\t\t\t$(\"#modalform\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#inputModal').addClass('top_menu_active');\r\n");
      out.write("\t\t$('#inputModal').find('i').addClass('menu_icon_active');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t $( \"#project_str_date\" ).datepicker();\r\n");
      out.write("\t\t $( \"#project_str_date\" ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\t\t $( \"#project_end_date\" ).datepicker();\r\n");
      out.write("\t\t $( \"#project_end_date\" ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\t\t $( \"#proj_str_date\" ).datepicker();\r\n");
      out.write("\t\t $( \"#proj_str_date\" ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\t\t $( \"#proj_end_date\" ).datepicker();\r\n");
      out.write("\t\t $( \"#proj_end_date\" ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\t});\r\n");
      out.write("</script> \r\n");
      out.write("</head>\r\n");
      out.write("<!-------------------------------- body ---------------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.hidden_myPage > a { text-decoration: none;\r\n");
      out.write("    \tcolor: black;\r\n");
      out.write("      }\r\n");
      out.write("    .hidden_myPage > a:hover {color:white;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"title\"><a class=\"title_logo\" href=\"/\"><span>D</span>djy</a></div>\r\n");
      out.write("    <div id=\"myPage\">\r\n");
      out.write("       <img src=\"/img/subpage/admin.png\" id=\"profile_photo\" /> \r\n");
      out.write("       <span>관리자님</span>\r\n");
      out.write("       <i class=\"fa fa-angle-down down_arrow\" style=\"font-size:24px;\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hidden_myPage\">\r\n");
      out.write("\t       <!-- <div>정보변경</div> -->\r\n");
      out.write("\t       <div><a href=\"/Logout\">로그아웃</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main_templet\">\r\n");
      out.write("\t\t\t<div id=\"slide_btn\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- side_menu -->\r\n");
      out.write("\t\t\t<nav class=\"nav\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"top_menu_box\">\r\n");
      out.write("   <div id=\"commoncode\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-table menu_icon\"></i> \r\n");
      out.write("   \t\t<a href=\"/Commoncode\">신청관리</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"freeln\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-address-book-o\"></i>\r\n");
      out.write("  \t\t<a href=\"/Freeln\">프리랜서</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"project\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-calendar-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Project\">프로젝트</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"charge\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-user-circle\"></i>\r\n");
      out.write("   \t\t<a href=\"/Charge\">담당자</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"client\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-building-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Client\">고객사</a>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- main -->\r\n");
      out.write("\t\t\t<article>\r\n");
      out.write("\t\t\t\t<div class=\"tabs\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"content-wrapper\">\r\n");
      out.write("\t\t\t\t\t<!-- 테이블내용 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-fw fa-users\"></i> 프로젝트 관리\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"dataTable_wrapper\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dataTables_wrapper dt-bootstrap4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 col-md-11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"dataTable_filter\" class=\"dataTables_filter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>Search: <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"프로젝트명을 입력하세요\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"myInput\" onkeyup=\"myFunction()\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 col-md-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"myBtn\" data-toggle=\"modal\" data-target=\"#inputModal\">등록</button>\r\n");
      out.write("<!------------------------------------------------- The Modal 새프로젝트등록 -------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"modal fade\" id=\"inputModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"modal-content modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t          <h5><i class=\"fa fa-user icon\"></i>등록</h5>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t\t          <form role=\"form\" action=\"/ProjectNewInsert\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t             <!--  <label for=\"proj_id\">프로젝트 코드</label> -->\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"hidden\" class=\"form-control\" id=\"project_id\" placeholder=\"자동생성\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"proj_nm\">프로젝트명</label>\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\" name=\"proj_nm\"class=\"form-control\" id=\"project_nm\" placeholder=\"프로젝트 이름을 입력하세요\" required>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"proj_date\">프로젝트 기간</label>\r\n");
      out.write("\t\t\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t              \t  <div>\r\n");
      out.write("\t\t\t\t\t\t              \t\t<input type=\"text\" name=\"proj_str_date\" class=\"form-control\" id=\"project_str_date\" style=\"width:48%; float:left;\" placeholder=\"시작일을 입력하세요\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t              \t\t<input type=\"text\" name=\"proj_end_date\" class=\"form-control\" id=\"project_end_date\" style=\"width:48%; float:right;\" placeholder=\"종료일을 입력하세요\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t              \t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t             <!-- <input type=\"hidden\" id=\"client_id\" name=\"client_id\" value=\"\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"client_id\">고객사</label>\r\n");
      out.write("\t\t\t\t                \t       <select name=\"client_id\" class=\"form-control\" id=\"client_id\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <option value=\"선택하세요\">선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t                \t      </select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t                \t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"involve_num\">인원</label>\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\" name=\"involve_num\" class=\"form-control\" id=\"involve_num\" placeholder=\"투여인원을 입력하세요\" required>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"field\"> 해당분야</label>\r\n");
      out.write("\t\t\t\t\t\t\t              \t   <div> <select name=\"field_1\" class=\"form-control\" id=\"field_1\" style=\"width:46%; float:left; margin-left:10px;\" required>\r\n");
      out.write("\t    \t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t\t\t\t              \t    <select name=\"field_2\" class=\"form-control\" id=\"field_2\" style=\"width:46%; float:right; margin-right:10px;\" required>\r\n");
      out.write("\t    \t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t\t\t </select></div>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <label for=\"note\">비고</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input type=\"text\" name=\"note\" class=\"form-control\" id=\"note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <label for=\"remark\">내용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <textarea name=\"remark\" class=\"form-control\" id=\"remark\" required></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"need_tech\">필요기술</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <textarea name=\"need_tech\" class=\"form-control\" id=\"need_tech\" required></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   </div>  \r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t   \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <label for=\"charge_id\" >담당자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"charge_id\" name=\"charge_id\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    </div> -->\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\t\t\t   <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <!-- <input type=\"hidden\" id=\"charge_id\" name=\"charge_id\" value=\"\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"charge_nm\">담당자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <select name=\"charge_id\" class=\"form-control\" id=\"charge_id\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t<option value=\"선택하세요\">선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t <label for=\"project_amount\">금액</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"project_amount\" name=\"project_amount\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  </div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"use_yn\">사용유무</label> <input id=\"use_yn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"use_yn\" value=\"Y\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-default pull-left\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger btn-default pull-left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("<!------------------------------------------------- The Modal 새프로젝트등록!!!끝 -------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<!----------------------------------------- The Modal 수정/삭제 ------------------>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("  \t\t\t\t\t\t\t  <div class=\"modal fade\" id=\"inputModal2\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t      <!-- Modal content2-->\r\n");
      out.write("\t\t \t\t\t\t\t      <div class=\"modal-content modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t          <h5><i class=\"fa fa-user icon\"></i>수정/삭제</h5>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t          <form id=\"modalform\" role=\"form\" action=\"ProjectNewInsert\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"proj_id\">프로젝트 코드</label>\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\" class=\"form-control\" id=\"proj_id\" name=\"proj_id\" placeholder=\"자동생성\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"proj_nm\">프로젝트명</label>\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\" class=\"form-control\" id=\"proj_nm\" name=\"proj_nm\" placeholder=\"프로젝트 이름을 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t              \r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t               <label for=\"proj_date\">프로젝트 기간</label>\r\n");
      out.write("\t\t\t\t\t\t\t             <div>\r\n");
      out.write("\t\t\t\t\t\t\t             \t<input type=\"text\" class=\"form-control\" id=\"proj_str_date\"  name=\"proj_str_date\" style=\"width:48%; float:left;\" placeholder=\"시작일을 입력하세요\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t             \t<input type=\"text\" class=\"form-control\" id=\"proj_end_date\" name=\"proj_end_date\"  style=\"width:48%; float:right;\" placeholder=\"종료일을 입력하세요\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t             </div>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"cli_id\">고객사</label>\r\n");
      out.write("\t\t\t\t\t\t\t           \t  <select name=\"client_id\" class=\"form-control\" id=\"cli_id\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t                \t      </select>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"inv_num\">인원</label>\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\" class=\"form-control\" id=\"inv_num\" name=\"involve_num\"  placeholder=\"투여인원을 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t              <label for=\"field\"> 해당분야</label>\r\n");
      out.write("\t\t\t\t\t\t\t              \t   <div> <select class=\"form-control\" id=\"fid_1\" name=\"field_1\" style=\"width:46%; float:left; margin-left:10px;\">\r\n");
      out.write("\t    \t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t\t\t\t              \t    <select class=\"form-control\" id=\"fid_2\" name=\"field_2\"  style=\"width:46%; float:right; margin-right:10px;\">\r\n");
      out.write("\t    \t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t\t\t </select></div>\r\n");
      out.write("\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <label for=\"nte\">비고</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"nte\" name=\"note\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <label for=\"rmark\">내용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <textarea class=\"form-control\" id=\"rmark\" name=\"remark\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"need_tech\">필요기술</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <textarea class=\"form-control\" id=\"need_tec\" name=\"need_tech\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   </div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"form-group\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t    <label for=\"char_id\" >담당자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"char_id\" name=\"charge_id\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <!--담당자 이름-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"char_id\">담당자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <select class=\"form-control\" id=\"char_id\" name=\"charge_id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t");
      if (_jspx_meth_c_005fforEach_005f7(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <label for=\"proj_amount\">금액</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"proj_amount\" name=\"project_amount\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t<label for=\"use_yn\">사용유무</label>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t\t\t<input id=\"us_yn\" type=\"checkbox\" name=\"use_yn\" value=\"Y\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t          \t\t<input type=\"button\" id=\"updatebtn\" class=\"btn btn-success btn-default pull-left\" value=\"수정\">\r\n");
      out.write("\t\t\t\t\t\t\t          \t\t<input type=\"button\" id=\"deletebtn\" class=\"btn btn-danger btn-default pull-left\" value=\"삭제\">\r\n");
      out.write("\t\t\t\t\t\t\t          \t\t<button type=\"\" class=\"btn btn-primary  btn-default pull-left\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t\t        \t</div>   \r\n");
      out.write("\t\t\t\t\t\t\t          </form>\r\n");
      out.write("\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t    </div>\r\n");
      out.write("<!----------------------------------------- The Modal 수정/삭제 !!! 끝 ------------------>\r\n");
      out.write("\r\n");
      out.write("<!----------------------------------------- The Modal 상세내용 ------------------>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("  \t\t\t\t\t\t\t  <div class=\"modal fade\" id=\"inputModal3\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t      <!-- Modal content3-->\r\n");
      out.write("\t\t \t\t\t\t\t      <div class=\"modal-content modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t          <h5><i class=\"fa fa-user icon\"></i>상세보기</h5>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t          <form id=\"modalform\" role=\"form\" action=\"\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t           \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <label for=\"rmark\">상세보기</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <textarea class=\"form-control\" id=\"rmark\" style=\"height:250px;\" name=\"remark\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t            <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t          \t\t<button type=\"\" class=\"btn btn-primary  btn-default pull-left\" data-dismiss=\"modal\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t\t        \t</div>   \r\n");
      out.write("\t\t\t\t\t\t\t          </form>\r\n");
      out.write("\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t    </div>\r\n");
      out.write("<!----------------------------------------- The Modal 상세내용 !!! 끝 ------------------>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table class=\"table table-bordered dataTable\" id=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\twidth=\"100%\" cellspacing=\"0\" role=\"grid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\taria-describedby=\"dataTable_info\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr role=\"row\" style=\"text-align: center; font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(0)\" style=\"width: 6%; height: 5%\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(1)\" style=\"width: 17%; height: 5%\">프로젝트명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(2)\" style=\"width: 12%; height: 5%\">프로젝트기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <th onclick=\"sortTable(3)\">프로젝트종료일</th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(3)\" style=\"width: 10%; height: 5%\">고객사</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(4)\" style=\"width: 17%; height: 5%\">필요기술</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(5)\" style=\"width: 10%; height: 5%\">해당분야</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(6)\" style=\"width: 6%; height: 5%\">투여인원</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(7)\" style=\"width: 10%; height: 5%\">담당자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t <th onclick=\"sortTable(8)\" style=\"width: 6%; height: 5%\">금액</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(9)\" style=\"width: 6%; height: 5%\">상세내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr role=\"row\" style=\"text-align: center; font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(0)\" rowspan=\"1\" colspan=\"1\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(1)\" rowspan=\"1\" colspan=\"1\">프로젝트명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(2)\" rowspan=\"1\" colspan=\"1\">프로젝트기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!--  <th onclick=\"sortTable(3)\" rowspan=\"1\" colspan=\"1\">프로젝트종료일</th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(3)\" rowspan=\"1\" colspan=\"1\">고객사</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(4)\" rowspan=\"1\" colspan=\"1\">필요기술</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(5)\" rowspan=\"1\" colspan=\"1\">해당분야</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(6)\" rowspan=\"1\" colspan=\"1\">투여인원</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(7)\" rowspan=\"1\" colspan=\"1\">담당자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    <th onclick=\"sortTable(8)\" rowspan=\"1\" colspan=\"1\">금액</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th onclick=\"sortTable(9)\" rowspan=\"1\" colspan=\"1\">상세내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 테이블내용 끝 -->\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(367,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("clientList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(367,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(367,14) '${clientList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${clientList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientList.client_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientList.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(380,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("projectList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(380,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(380,15) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(385,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("projectList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(385,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(385,15) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(411,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("chargeList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(411,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(411,20) '${chargeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${chargeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chargeList.charge_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chargeList.charge_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(470,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("clientList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(470,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(470,14) '${clientList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${clientList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientList.client_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientList.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(482,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("projectList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(482,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(482,15) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f6 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f6_reused = false;
    try {
      _jspx_th_c_005fforEach_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f6.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(487,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setVar("projectList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(487,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(487,15) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f6 = _jspx_th_c_005fforEach_005f6.doStartTag();
        if (_jspx_eval_c_005fforEach_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectList.field_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f6);
      _jspx_th_c_005fforEach_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f7 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f7_reused = false;
    try {
      _jspx_th_c_005fforEach_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f7.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(513,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setVar("chargeList");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(513,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(513,15) '${chargeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${chargeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f7 = _jspx_th_c_005fforEach_005f7.doStartTag();
        if (_jspx_eval_c_005fforEach_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chargeList.charge_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chargeList.charge_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f7.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f7);
      _jspx_th_c_005fforEach_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f8 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f8_reused = false;
    try {
      _jspx_th_c_005fforEach_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f8.setParent(null);
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(613,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setVar("proj");
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(613,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/02_PROJECT/project.jsp(613,13) '${projectList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/ADMIN/02_PROJECT/project.jsp(613,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f8 = _jspx_th_c_005fforEach_005f8.doStartTag();
        if (_jspx_eval_c_005fforEach_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"rowClick\" role=\"row\" style=\"text-align: center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" data-toggle=\"modal\" class=\"idClick proj_id\" data-target=\"#inputModal2\" data-id=\"proj_id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.proj_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" data-toggle=\"modal\" class=\"idClick charge_id\" data-target=\"#inputModal2\" data-id=\"charge_id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.charge_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" data-toggle=\"modal\" class=\"idClick client_id\" data-target=\"#inputModal2\" data-id=\"client_id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.client_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" data-toggle=\"modal\" class=\"idClick field_2\" data-target=\"#inputModal2\" data-id=\"field_2\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.field_2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick rownum\" data-target=\"#inputModal2\"data-id=\"rownum\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.rownum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick proj_nm\" data-target=\"#inputModal2\"data-id=\"proj_nm\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.proj_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick proj_str_date\" data-target=\"#inputModal2\" data-id=\"proj_str_date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.proj_str_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t~\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" class=\"idClick proj_end_date\" data-target=\"#inputModal2\" data-id=\"proj_end_date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.proj_end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick client_id\" data-target=\"#inputModal2\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.client_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick need_tech\" data-target=\"#inputModal2\" data-id=\"need_tech\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.need_tech}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick field_1\" data-target=\"#inputModal2\" data-id=\"field_1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.field_1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick involve_num\" data-target=\"#inputModal2\" data-id=\"involve_num\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.involve_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick charge_id\" data-target=\"#inputModal2\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.charge_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t <td><a href=\"#\" data-toggle=\"modal\" class=\"idClick project_amount\" data-target=\"#inputModal2\" data-id=\"project_amount\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.project_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" data-toggle=\"modal\" class=\"idClick remark\" data-target=\"#inputModal3\" data-id=\"remark\">상세내용<p hidden>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proj.remark}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p></a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f8.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f8);
      _jspx_th_c_005fforEach_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f8_reused);
    }
    return false;
  }
}
