/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-23 01:46:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.LOGIN;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/1/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1540099427413L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script> \r\n");
      out.write("    <!-- Bootstrap core CSS-->\r\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template-->\r\n");
      out.write("    <link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template-->\r\n");
      out.write("    <link href=\"css/mainpage/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- Jquery min.js 링크-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- datepicker를 위한 링크 시작 -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("  \t<!-- <link rel=\"stylesheet\" href=\"/resources/demos/style.css\"> -->\r\n");
      out.write("\r\n");
      out.write("  \t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  \t<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction registerCheckFunction() {\r\n");
      out.write("\t\tvar userID = $('#inputId').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:'POST',\r\n");
      out.write("\t\t\turl:'./Register',\r\n");
      out.write("\t\t\tdata:{inputId:inputId},\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tif(result ==1 ){\r\n");
      out.write("\t\t\t\t\t$('#checkMessage').html('사용할 수 있는 아이디입니다.');\r\n");
      out.write("\t\t\t\t\t$('#checkType').attr('class','modal-content panel-success');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#checkMessage').html('사용할 수 없는 아이디입니다.');\r\n");
      out.write("\t\t\t\t\t$('#checkType').attr('class','modal-content panel-warning');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#checkModal').modal(\"show\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction passwordCheckFunction(){\r\n");
      out.write("\t\tvar userPassword1 = $('#freeln_pwd').val();\r\n");
      out.write("\t\tvar userPassword2 = $('#confirmPwd').val();\r\n");
      out.write("\t\tif(freeln_pwd != confirmPwd){\r\n");
      out.write("\t\t\t$('#passwordCheckMessage').html('비밀번호가 서로 일치하지 않습니다.');\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#passwordCheckMessage').html('');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>  \t\r\n");
      out.write("<!-- datepicker를 위한 링크 끝 -->\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t   $('#upload').change(function(){\r\n");
      out.write("\t    var input = this;\r\n");
      out.write("\t    var url = $(this).val();\r\n");
      out.write("\t    var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();\r\n");
      out.write("\t    if (input.files && input.files[0]&& (ext == \"gif\" || ext == \"png\" || ext == \"jpeg\" || ext == \"jpg\")) \r\n");
      out.write("\t     {\r\n");
      out.write("\t        var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("\t        reader.onload = function (e) {\r\n");
      out.write("\t           $('#img').attr('src', e.target.result);\r\n");
      out.write("\t        }\r\n");
      out.write("\t       reader.readAsDataURL(input.files[0]);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else\r\n");
      out.write("\t    {\r\n");
      out.write("\t      $('#img').attr('src', 'img/mainpage/avatar.png');\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }); \r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 데이트 피커 시작 -->\r\n");
      out.write("<script>\r\n");
      out.write(" \r\n");
      out.write("\t(function($) { $(document).ready(function(){\r\n");
      out.write("\t\t$('#work_str_date').datepicker();\r\n");
      out.write("\t\t$('#work_str_date' ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\t\t$('#work_end_date').datepicker();\r\n");
      out.write("\t\t$('#work_end_date' ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("  \t\t});\r\n");
      out.write("\t})(jQuery);\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 데이트 피커 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 아이디 중복 체크 시작-->\r\n");
      out.write("<script>\r\n");
      out.write("//아이디 체크여부 확인 (아이디 중복일 경우 = 0 , 중복이 아닐경우 = 1 )\r\n");
      out.write("var idck = 0;\r\n");
      out.write("$(function() {\r\n");
      out.write("    //idck 버튼을 클릭했을 때 \r\n");
      out.write("    $(\"#idDoubleCheck\").click(function() {\r\n");
      out.write("        \r\n");
      out.write("        //userid 를 param.\r\n");
      out.write("        var userid =  $(\"#freeln_phone\").val(); \r\n");
      out.write("        \r\n");
      out.write("        $.ajax({\r\n");
      out.write("            async: true,\r\n");
      out.write("            type : 'POST',\r\n");
      out.write("            data : userid,\r\n");
      out.write("            url : \"IdDoubleCheck\",\r\n");
      out.write("            dataType : \"json\",\r\n");
      out.write("            contentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("            success : function(data) {\r\n");
      out.write("                if (data.cnt > 0) {\r\n");
      out.write("                    \r\n");
      out.write("                    alert(\"핸드폰번호가 존재합니다. 다른 핸드폰번호를 입력해주세요.\");\r\n");
      out.write("                    $(\"#freeln_phone\").focus();\r\n");
      out.write("                    \r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"사용가능한 핸드폰번호입니다.\");\r\n");
      out.write("                    $(\"#freeln_mail\").focus();\r\n");
      out.write("                    //아이디가 중복하지 않으면  idck = 1 \r\n");
      out.write("                    idck = 1;\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error : function(error) {\r\n");
      out.write("                \r\n");
      out.write("                alert(\"error : \" + error);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 아이디 중복 체크 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-dark\">\r\n");

	String freeln_phone = null;
	if(session.getAttribute("freeln_phone") != null){
		freeln_phone = (String) session.getAttribute("freeln_phone");
	if(freeln_phone != null){
		session.setAttribute("messageType", "오류메시지");
		session.setAttribute("messageContent", "로그인이 되어 있는 상태입니다.");
		response.sendRedirect("index.jsp");
		return;
	 	}
	}
	
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"card card-register mx-auto mt-5\">\r\n");
      out.write("\t\t\t<div class=\"card-header\">Register an Account</div>\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<!-- <form method=\"POST\" action=\"/SubPage\"> -->\r\n");
      out.write("\t\t\t\t<form action=\"/NewFreeLnRegist\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 사진입력 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img\" alt=\"사진을 올려주세요\"  src=\"#\" width=\"225\" height=\"300\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" id=\"upload\" name=\"img_nm\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 사진입력 끝 -->\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t<!-- 이름, 전화번호 입력 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"freeln_nm\" name=\"freeln_nm\" class=\"form-control\" placeholder=\"Full name\" required=\"required\" autofocus=\"autofocus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"freeln_nm\">Full name</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"freeln_phone\" name=\"freeln_phone\" class=\"form-control\" placeholder='\"-\"없이 입력하세요' required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"freeln_phone\">핸드폰번호 : \"-\"없이 입력하세요</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"idDoubleCheck\" type=\"button\" value=\"중복확인\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 이름, 전화번호 입력 끝 -->\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\t<!-- 이메일 입력 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" id=\"freeln_mail\" name=\"freen_mail\" class=\"form-control\" placeholder=\"Email address\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"freeln_mail\">Email address</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 이메일 입력 끝-->\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\t<!-- 비밀번호 입력 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"freeln_pwd\" name=\"freeln_pwd\" class=\"form-control\" placeholder=\"Password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"freeln_pwd\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"confirmPwd\" class=\"form-control\" placeholder=\"Confirm password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"confirmPwd\">Confirm password</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 비밀번호 입력 끝-->\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\t<!-- 희망근무지역, 희망월급여 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"hope_place\" name=\"hope_place\" class=\"form-control\" placeholder=\"Hope working area\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"hope_place\">Hope working area</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"hope_money\" name=\"hope_money\" class=\"form-control\" placeholder=\"Desired wage\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"hope_money\">Desired wage</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<!-- 희망근무지역, 희망월급여 끝-->\r\n");
      out.write("            \r\n");
      out.write("<!------------------------  select 기술정보 입력1 -------------------->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card-header\">Technical information 개발 언어 선택</div>\r\n");
      out.write(" <br>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"col-md-12\">\r\n");
      out.write(" <div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write(" <label for=\"technic_1\">\r\n");
      out.write("\t<select id=\"technic_1\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">.NET</option>\r\n");
      out.write("\t\t    <option value=\".NET초급\">초급</option>\r\n");
      out.write("\t        <option value=\".NET중급\">중급</option>\r\n");
      out.write("\t        <option value=\".NET고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t <label for=\"technic_2\">\r\n");
      out.write("\t<select id=\"technic_2\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">C</option>\r\n");
      out.write("\t\t    <option value=\"C초급\">초급</option>\r\n");
      out.write("\t        <option value=\"C중급\">중급</option>\r\n");
      out.write("\t        <option value=\"C고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_3\">\r\n");
      out.write("\t<select id=\"technic_3\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">C#</option>\r\n");
      out.write("\t\t    <option value=\"C#초급\">초급</option>\r\n");
      out.write("\t        <option value=\"C#중급\">중급</option>\r\n");
      out.write("\t        <option value=\"C#고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_4\">\r\n");
      out.write("\t<select id=\"technic_4\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">C++</option>\r\n");
      out.write("\t\t    <option value=\"C++초급\">초급</option>\r\n");
      out.write("\t        <option value=\"C++중급\">중급</option>\r\n");
      out.write("\t        <option value=\"C++고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_5\">\r\n");
      out.write("\t<select id=\"technic_5\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">JAVA</option>\r\n");
      out.write("\t\t    <option value=\"JAVA초급\">초급</option>\r\n");
      out.write("\t        <option value=\"JAVA중급\">중급</option>\r\n");
      out.write("\t        <option value=\"JAVA고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_6\">\r\n");
      out.write("\t<select id=\"technic_6\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">JS</option>\r\n");
      out.write("\t\t    <option value=\"JS초급\">초급</option>\r\n");
      out.write("\t        <option value=\"JS중급\">중급</option>\r\n");
      out.write("\t        <option value=\"JS고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_7\">\r\n");
      out.write("\t<select id=\"technic_7\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">JSP</option>\r\n");
      out.write("\t\t    <option value=\"JSP초급\">초급</option>\r\n");
      out.write("\t        <option value=\"JSP중급\">중급</option>\r\n");
      out.write("\t        <option value=\"JSP고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_8\">\r\n");
      out.write("\t<select id=\"technic_8\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">SPRING</option>\r\n");
      out.write("\t\t    <option value=\"SPRING초급\">초급</option>\r\n");
      out.write("\t        <option value=\"SPRING중급\">중급</option>\r\n");
      out.write("\t        <option value=\"SPRING고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_9\">\r\n");
      out.write("\t<select id=\"technic_9\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">PHP</option>\r\n");
      out.write("\t\t    <option value=\"PHP초급\">초급</option>\r\n");
      out.write("\t        <option value=\"PHP중급\">중급</option>\r\n");
      out.write("\t        <option value=\"PHP고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_10\">\r\n");
      out.write("\t<select id=\"technic_10\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">ORACLE</option>\r\n");
      out.write("\t\t    <option value=\"ORACLE초급\">초급</option>\r\n");
      out.write("\t        <option value=\"ORACLE중급\">중급</option>\r\n");
      out.write("\t        <option value=\"ORACLE고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_11\">\r\n");
      out.write("\t<select id=\"technic_11\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">PHP</option>\r\n");
      out.write("\t\t    <option value=\"MYSQL초급\">초급</option>\r\n");
      out.write("\t        <option value=\"MYSQL중급\">중급</option>\r\n");
      out.write("\t        <option value=\"MYSQL고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_12\">\r\n");
      out.write("\t<select id=\"technic_12\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">MSSQL</option>\r\n");
      out.write("\t\t    <option value=\"MSSQL\">초급</option>\r\n");
      out.write("\t        <option value=\"MSSQL중급\">중급</option>\r\n");
      out.write("\t        <option value=\"MSSQL고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_13\">\r\n");
      out.write("\t<select id=\"technic_13\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">ANDROID</option>\r\n");
      out.write("\t\t    <option value=\"ANDROID초급\">초급</option>\r\n");
      out.write("\t        <option value=\"ANDROID중급\">중급</option>\r\n");
      out.write("\t        <option value=\"ANDROID고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t\t</div>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card-header\">Technical information 디자인 개발 언어 선택</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_14\">\r\n");
      out.write("\t\t\t<select style=\"display:inline-block; overflow:hidden;\" id=\"technic_14\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t\t\t<option  value=\"\">HTML5</option>\r\n");
      out.write("\t\t\t\t    <option value=\".NET초급\">초급</option>\r\n");
      out.write("\t\t\t        <option value=\".NET중급\">중급</option>\r\n");
      out.write("\t\t\t        <option value=\".NET고급\">고급</option>\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div class=\"col-md-3\" style=\"float:left;\">\r\n");
      out.write("\t\t<label for=\"technic_15\">\r\n");
      out.write("\t<select  style=\"display:inline-block; overflow:hidden;\" id=\"technic_15\" name=\"major_tech\" class=\"form-control\" >\r\n");
      out.write("\t\t\t<option value=\"\">PHOTOSHOP</option>\r\n");
      out.write("\t\t    <option value=\"PHOTOSHOP초급\">초급</option>\r\n");
      out.write("\t        <option value=\"PHOTOSHOP중급\">중급</option>\r\n");
      out.write("\t        <option value=\"PHOTOSHOP고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"col-md-3\"  style=\"float:left;\">\t\r\n");
      out.write("\t\t<label for=\"technic_16\" >\r\n");
      out.write("\t<select id=\"technic_16\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">ILLUST</option>\r\n");
      out.write("\t\t    <option value=\"ILLUST초급\">초급</option>\r\n");
      out.write("\t        <option value=\"ILLUST중급\">중급</option>\r\n");
      out.write("\t        <option value=\"ILLUST고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"col-md-3\"  style=\"float:left;\">\t\r\n");
      out.write("\t\t<label for=\"technic_17\" >\r\n");
      out.write("\t<select id=\"technic_17\" name=\"major_tech\" class=\"form-control\">\r\n");
      out.write("\t\t\t<option value=\"\">CSS</option>\r\n");
      out.write("\t\t    <option value=\"ILLUST초급\">초급</option>\r\n");
      out.write("\t        <option value=\"ILLUST중급\">중급</option>\r\n");
      out.write("\t        <option value=\"ILLUST고급\">고급</option>\t\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!---------   기타언어 입력 ----------->\r\n");
      out.write("\t<div class=\"card-header\" style=\"clear:both;\">Technical information 기타 기술정보</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"technic_18\" name=\"major_tech\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t<label for=\"technic_18\">항목에 없는 기술정보를 입력하세요</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!---------   기타언어 입력 끝----------->\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("            \r\n");
      out.write("<!---------------------------- 기술정보 입력 끝----------------------->\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("<!---------------------- 경력정보 입력 ------------------------->\r\n");
      out.write("<div class=\"card-header\">Experience information</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("\t<div class=\"form-row\">\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"client_nm\" name=\"client_nm\" class=\"form-control\" placeholder=\"Client Name\" required=\"required\" autofocus=\"autofocus\">\r\n");
      out.write("\t\t\t\t<label for=\"client_nm\">Client Name</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t <div class=\"col-md-3\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"cli_loca_1\" name=\"client_local_1\" class=\"form-control\" placeholder=\"광역시,도\" autofocus=\"autofocus\">\r\n");
      out.write("\t\t\t\t<label for=\"cli_loca_1\">광역시,도</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t <div class=\"col-md-3\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"cli_loca_2\" name=\"client_local_2\" class=\"form-control\" placeholder=\"시군구\"  autofocus=\"autofocus\">\r\n");
      out.write("\t\t\t\t<label for=\"cli_loca_2\">시군구</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br><br> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"duty\" name=\"duty\" class=\"form-control\" placeholder=\"duty\" required=\"required\">\r\n");
      out.write("\t\t\t\t<label for=\"duty\">Duty</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"task\" name=\"task\" class=\"form-control\" placeholder=\"task\" required=\"required\">\r\n");
      out.write("\t\t\t\t<label for=\"task\">Task</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"work_str_date\" name=\"work_str_date\" class=\"form-control\" placeholder=\"datepicker\" required=\"required\"/>              \r\n");
      out.write("\t\t\t\t<label for=\"work_str_date\">Work Start Date</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"work_end_date\" name=\"work_end_date\" class=\"form-control\" placeholder=\"work_end_date\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t<label for=\"work_end_date\">Work end date</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<textarea id=\"contents\" name=\"contents\" class=\"form-control\" placeholder=\"상세 개발 내용 기입\" required=\"required\"></textarea>\r\n");
      out.write("\t\t\t\t<label for=\"contents\"></label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"use_tech_1\" name=\"use_tech_1\" class=\"form-control\" placeholder=\"Main Technical Language\"/>\r\n");
      out.write("\t\t\t\t<label for=\"use_tech_1\">Main Technical Language</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"use_tech_2\" name=\"use_tech_2\" class=\"form-control\" placeholder=\"Sub Technical Language\"/>\r\n");
      out.write("\t\t\t\t<label for=\"use_tech_2\">Sub Technical Language</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>               \r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"form-label-group\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"work_money\" name=\"work_money\" class=\"form-control\" placeholder=\"Work money\"/>\r\n");
      out.write("\t\t\t\t<label for=\"work_money\">Work money</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---------------------- 경력정보 입력 끝------------------------->\r\n");
      out.write("\r\n");
      out.write("          \t\t<!-- <input class=\"btn btn-primary btn-block\" type=\"submit\" value=\"회원가입\"> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\t\t\t\t<!-- <a class=\"btn btn-primary btn-block\" href=\"login.html\">Register</a> -->\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary btn-block\" >Register</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t<a class=\"d-block small mt-3\" href=\"/\">Login Page</a>\r\n");
      out.write("\t\t\t\t<a class=\"d-block small\" href=\"/Forgot-password\">Forgot Password?</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	String messageContent = null;
	if(session.getAttribute("messageContent") != null) {
		messageContent = (String) session.getAttribute("messageContent");
	}	
	String messageType = null;
	if(session.getAttribute("messageType") != null) {
		messageType = (String) session.getAttribute("messageType");
	}	
	if (messageContent != null){
	
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"messageModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"vertical-alignment-helper\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog vertical-align-center\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" ");
if(messageType.equals("오류메시지")) out.println("panel-warning"); else out.println("panel-success"); 
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">close</span>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( messageType );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( messageContent);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">확인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#messageModal').modal(\"show\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

	session.removeAttribute("messageContent");
	session.removeAttribute("messageType");
	}
	
      out.write("\t\r\n");
      out.write("\t<div class=\"modal fade\" id=\"checkModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"vertical-alignment-helper\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog vertical-align-center\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content panel-info\" id=\"checkType\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">close</span>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t확인메시지\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\" id=\"checkMessage\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">확인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
