/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-10-23 01:42:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ADMIN._00_005fCOMMON;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class commoncode_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/ADMIN/00_COMMON/../include/header.jspf", Long.valueOf(1540236092000L));
    _jspx_dependants.put("/WEB-INF/views/ADMIN/00_COMMON/../include/nav.jspf", Long.valueOf(1540244370115L));
    _jspx_dependants.put("jar:file:/C:/Users/1/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1540099427413L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>계약관리</title>\r\n");
      out.write("\t<!-- 테이블관련 CSS/JS 시작 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core CSS-->\r\n");
      out.write("\t<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"vendor/datatables/dataTables.bootstrap4.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/mainpage/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("    <script src=\"vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"vendor/datatables/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("    <script src=\"js/mainpage/sb-admin.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  \t<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \t<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 테이블관련 CSS/JS 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/include/subpage.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- js -->\r\n");
      out.write("\t<script src=\"js/include/subpage.js\"></script>\r\n");
      out.write("\t<!-- 메뉴버튼눌렀을때 HOVER 유지 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#commoncode').addClass('top_menu_active');\r\n");
      out.write("\t\t$('#commoncode').find('i').addClass('menu_icon_active');\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- 메뉴버튼눌렀을때 HOVER 유지 끝-->\r\n");
      out.write("\t\r\n");
      out.write("<!-- 테이블 내용에서 고객사로 검색 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t  var input, filter, table, tr, i;\r\n");
      out.write("\t  var freeln_nm,career_year, freeln_phone,in_enable_date,freen_mail,hope_place,major_tech;\r\n");
      out.write("\t  input = document.getElementById(\"myInput\");\r\n");
      out.write("\t  filter = input.value.toUpperCase();\r\n");
      out.write("\t  tbody = $('tbody');\r\n");
      out.write("\t  tr = $('tr',tbody);\r\n");
      out.write("\t  project_nm = $('.project_nm');\r\n");
      out.write("\t  /* career_year = $('.career_year');\r\n");
      out.write("\t  freeln_phone = $('.freeln_phone');\r\n");
      out.write("\t  in_enable_date = $('.in_enable_date');\r\n");
      out.write("\t  freen_mail = $('.freen_mail');\r\n");
      out.write("\t  hope_place = $('.hope_place');\r\n");
      out.write("\t  major_tech = $('.major_tech'); */\r\n");
      out.write("\r\n");
      out.write("\t  for (i = 0; i < tr.length; i++) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t      if (project_nm.eq(i).html().toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("\t    \t  tr.eq(i).attr('style','display:');\r\n");
      out.write("\t      } else {\r\n");
      out.write("\t    \t  tr.eq(i).attr('style','display:none');\r\n");
      out.write("\t      }\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- 테이블 내용에서 고객사로 검색 끝-->\r\n");
      out.write("\r\n");
      out.write("<!-- 테이블 내용에서 컬럼클릭시 정렬 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction sortTable(n) {\r\n");
      out.write("\t  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;\r\n");
      out.write("\t  table = document.getElementById(\"dataTable\");\r\n");
      out.write("\t  switching = true;\r\n");
      out.write("\t  dir = \"asc\"; \r\n");
      out.write("\t  while (switching) {\r\n");
      out.write("\t    switching = false;\r\n");
      out.write("\t    rows = table.rows;\r\n");
      out.write("\t    for (i = 1; i < (rows.length - 1); i++) {\r\n");
      out.write("\t\r\n");
      out.write("\t      shouldSwitch = false;\r\n");
      out.write("\t      x = rows[i].getElementsByTagName(\"TD\")[n];\r\n");
      out.write("\t      y = rows[i + 1].getElementsByTagName(\"TD\")[n];\r\n");
      out.write("\t      if (dir == \"asc\") {\r\n");
      out.write("\t        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {\r\n");
      out.write("\t          shouldSwitch= true;\r\n");
      out.write("\t          break;\r\n");
      out.write("\t        }\r\n");
      out.write("\t      } else if (dir == \"desc\") {\r\n");
      out.write("\t        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {\r\n");
      out.write("\t          shouldSwitch = true;\r\n");
      out.write("\t          break;\r\n");
      out.write("\t        }\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if (shouldSwitch) {\r\n");
      out.write("\t      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);\r\n");
      out.write("\t      switching = true;\r\n");
      out.write("\t      switchcount ++;      \r\n");
      out.write("\t    } else {\r\n");
      out.write("\t      if (switchcount == 0 && dir == \"asc\") {\r\n");
      out.write("\t        dir = \"desc\";\r\n");
      out.write("\t        switching = true;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- 테이블 내용에서 컬럼클릭시 정렬 끝-->\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$('#appupdate').on('click',function(){\r\n");
      out.write("\t\t/* var phone = $('#freeln_phone', this).html(); */\r\n");
      out.write("\t\tvar tr = $(this).parents('tr');\r\n");
      out.write("\t\tvar project_id = $('.project_id',tr).html();\r\n");
      out.write("\t\tvar freeln_id = $('.freeln_id',tr).html();\r\n");
      out.write("\t\t/* alert(project_id+freeln_id); */\r\n");
      out.write("\t\tlocation.href=\"/ApplyUpdate?project_id=\"+project_id+\"&freeln_id=\"+freeln_id ; \r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-------------------------------- body ---------------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<!-- header -->\r\n");
      out.write("  <header>\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.hidden_myPage > a { text-decoration: none;\r\n");
      out.write("    \tcolor: black;\r\n");
      out.write("      }\r\n");
      out.write("    .hidden_myPage > a:hover {color:white;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"title\"><a class=\"title_logo\" href=\"/\"><span>D</span>djy</a></div>\r\n");
      out.write("    <div id=\"myPage\">\r\n");
      out.write("       <img src=\"/img/subpage/admin.png\" id=\"profile_photo\" /> \r\n");
      out.write("       <span>관리자님</span>\r\n");
      out.write("       <i class=\"fa fa-angle-down down_arrow\" style=\"font-size:24px;\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hidden_myPage\">\r\n");
      out.write("\t       <!-- <div>정보변경</div> -->\r\n");
      out.write("\t       <div><a href=\"/Logout\">로그아웃</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </header>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"main_templet\">\r\n");
      out.write("  <div id=\"slide_btn\"></div>\r\n");
      out.write("   \r\n");
      out.write("<!-- side_menu -->\r\n");
      out.write("  <nav class=\"nav\">\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"top_menu_box\">\r\n");
      out.write("   <div id=\"commoncode\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-table menu_icon\"></i> \r\n");
      out.write("   \t\t<a href=\"/Commoncode\">신청관리</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"freeln\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-address-book-o\"></i>\r\n");
      out.write("  \t\t<a href=\"/Freeln\">프리랜서</a>\t  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"project\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-calendar-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Project\">프로젝트</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"charge\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-user-circle\"></i>\r\n");
      out.write("   \t\t<a href=\"/Charge\">담당자</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"client\" class=\"top_menu\">\r\n");
      out.write("   \t\t<i class=\"fa fa-building-o\"></i>\r\n");
      out.write("   \t\t<a href=\"/Client\">고객사</a>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("<!-- main -->\r\n");
      out.write("  <article>\r\n");
      out.write("   \t<div class=\"tabs\"></div>\r\n");
      out.write("    \t\r\n");
      out.write("    <div class=\"content-wrapper\"> \r\n");
      out.write("    <!-- 테이블내용 시작 -->\r\n");
      out.write("    \t<div class=\"card mb-3\">\r\n");
      out.write("    \t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t<i class=\"fas fa-fw fa-users\"></i>신청관리\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"card-body\">\r\n");
      out.write("    \t\t\t<div class=\"table-responsive\">\r\n");
      out.write("    \t\t\t\t<div id=\"dataTable_wrapper\" \r\n");
      out.write("    \t\t\t\t\tclass=\"dataTables_wrapper dt-bootstrap4\">\r\n");
      out.write("    \t\t\t\t\t<div class=\"row\">\t\t\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-12 col-md-11\">\r\n");
      out.write("\t    \t\t\t\t\t\t<div id=\"dataTable_filter\" class=\"dataTables_filter\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t<label>Search: <input type=\"text\"\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t class=\"form-control form-control-sm\" \r\n");
      out.write("    \t\t\t\t\t\t\t\t\t placeholder=\"프로젝트명을 입력하세요\" aria-controls=\"dataTable\" \r\n");
      out.write("    \t\t\t\t\t\t\t\t\t id=\"myInput\" onkeyup=\"myFunction()\">\r\n");
      out.write("\t    \t\t\t\t\t\t\t</label>\r\n");
      out.write("\t    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-12 col-md-1\">\t\r\n");
      out.write("    \t\t\t\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-primary btn-sm\" \r\n");
      out.write("    \t\t\t\t\t\t\t\tid=\"myBtn\" data-toggle=\"modal\" data-target=\"#inputModal\">등록</button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-------------------------- 조회 리스트 테이블---------------------------->\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("              \t\t\t</div>\r\n");
      out.write("           \t\t\t</div>\r\n");
      out.write("           \t\t\t<div class=\"row\">\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("    \t\t\t\t\t\t<table class=\"table table-bordered dataTable\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\" role=\"grid\" aria-describedby=\"dataTable_info\" style=\"width: 100%;\">\r\n");
      out.write("                  \t\t\t\t<thead>\r\n");
      out.write("                    \t\t\t\t<tr role=\"row\" style=\"text-align: center\">\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(0)\">순번</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(1)\">프로젝트ID</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(2)\">프로젝트명</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(3)\">프리랜서ID</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(4)\">프리랜서명</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(5)\">신청일</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(6)\">승인여부</th>\r\n");
      out.write("                    \t\t\t\t\t<th>승인</th>\r\n");
      out.write("                   \t\t\t\t \t</tr>\r\n");
      out.write("                  \t\t\t\t</thead>\r\n");
      out.write("                  \t\t\t\t<tfoot>\r\n");
      out.write("                    \t\t\t\t<tr role=\"row\" style=\"text-align: center\">\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(0)\">순번</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(1)\">프로젝트ID</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(2)\">프로젝트명</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(3)\">프리랜서ID</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(4)\">프리랜서명</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(5)\">신청일</th>\r\n");
      out.write("                    \t\t\t\t\t<th onclick=\"sortTable(6)\">승인여부</th>\r\n");
      out.write("                    \t\t\t\t\t<th>승인</th>\r\n");
      out.write("                    \t\t\t\t</tr>\r\n");
      out.write("                  \t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t                <tbody>\r\n");
      out.write("\t\t\t\t\t                  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t                </tbody>\r\n");
      out.write("                \t\t\t</table>\r\n");
      out.write("           \t\t\t\r\n");
      out.write("         \t  </div>\r\n");
      out.write("    \t\t</div>\t\t\t\r\n");
      out.write("   \t\t </div> \t\t\t\r\n");
      out.write(" \t </div> \t\r\n");
      out.write("   </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("   <!-- 테이블내용 끝 -->   \t\r\n");
      out.write("  </article>\r\n");
      out.write("</div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/ADMIN/00_COMMON/commoncode.jsp(215,23) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("app");
      // /WEB-INF/views/ADMIN/00_COMMON/commoncode.jsp(215,23) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ADMIN/00_COMMON/commoncode.jsp(215,23) '${ApplyList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ApplyList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/ADMIN/00_COMMON/commoncode.jsp(215,23) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t                  \t\t<tr class=\"rowClick\" role=\"row\" style=\"text-align:center\">\r\n");
            out.write("\t\t\t\t\t                  \t\t\t  \r\n");
            out.write("\t\t\t\t\t\t\t                      \r\n");
            out.write("\t\t\t\t\t\t\t                      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.rownum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td class=\"project_id\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.project_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td class=\"project_nm\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.project_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td class=\"freeln_id\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.freeln_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.freeln_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.apply_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.apply_yn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t                      <td><input type=\"button\" id=\"appupdate\" name=\"appupdate\" value=\"승인\"></td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t           \r\n");
            out.write("\t\t\t\t\t\t                    </tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
